language: java
jdk:
  - oraclejdk8
os:
  - linux

before_script:
  - curl https://www.jpm4j.org/install/script | sh
  - /home/travis/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

script: gradle test jacocoTestReport --info

after_script:
  - /home/travis/jpm/bin/codacy-coverage-reporter -l Java -r coverage.xml